fail_fast: false
exclude: ^(deploy/|migrations/)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.3.0"
    hooks:
      - id: check-case-conflict
        exclude_types: [c]
      - id: check-merge-conflict
        exclude_types: [c]
      - id: trailing-whitespace
        exclude_types: [c]
      - id: end-of-file-fixer
        exclude_types: [c]
      - id: mixed-line-ending
        exclude_types: [c]
      - id: name-tests-test
        exclude_types: [c]
      - id: check-ast
        exclude_types: [c]
      - id: check-toml
        exclude_types: [c]

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        exclude_types: [c]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]
        exclude_types: [c]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.982"
    hooks:
      - id: mypy
        args: ["--config-file", "pyproject.toml"]
        exclude_types: [c]
